name: Build PDF Parser EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypdf pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile main.py --name pdf_parser

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf-parser-exe
          path: dist/pdf_parser.exe
